<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/reality-icon.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/bootsnav.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/jquery.fancybox.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/owl.transitions.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/cubeportfolio.min.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/settings.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/range-Slider.min.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/search.css">
<link rel="stylesheet" type="text/css" href="{{asset('home')}}/css/style.css">